fix parsing error

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -23,13 +23,13 @@ before_install:
       export LD_LIBRARY_PATH=/opt/glibc-2.28/lib:$LD_LIBRARY_PATH && 
       exit"
 
- # Debugging: Check for the availability of apt-get and installed libraries
- - docker run --rm nimroda/docker-react bash -c "
- apt-get update && 
- apt-get install -y libxml2-dev libxslt-dev zlib1g-dev libssl-dev && 
- echo 'Dependencies installed successfully!' && 
- gem install nokogiri --platform=ruby || (echo 'Failed to install Nokogiri!' && exit 1)" 
- 
+  # Debugging: Check for the availability of apt-get and installed libraries
+  - docker run --rm nimroda/docker-react bash -c "
+    apt-get update && 
+    apt-get install -y libxml2-dev libxslt-dev zlib1g-dev libssl-dev && 
+    echo 'Dependencies installed successfully!' && 
+    gem install nokogiri --platform=ruby || (echo 'Failed to install Nokogiri!' && exit 1)" 
+
 script:
   - docker run -e CI=true nimroda/docker-react npm run test
 
